
-- WHO ARE THE HEALTH PERSONNELS IN CHARGE OF THE CHOLERA VACCINATION FOR EACH REGION AND STATE?--

SELECT * 
FROM DBO.HEALTHPERSONNEL HP
LEFT JOIN DBO.STATES S ON HP.REGIONCODE = S.REGIONCODE
JOIN DBO.REGIONS R ON R.ID = HP.REGIONCODE

SELECT HP.FULLNAME AS HEALTHPERSONNEL, HP.TITLE, S.STATENAME AS STATE, R.NAME AS REGION 
FROM DBO.HEALTHPERSONNEL HP
LEFT JOIN DBO.STATES S ON HP.REGIONCODE = S.REGIONCODE
JOIN DBO.REGIONS R ON R.ID = HP.REGIONCODE


--HOW MANY CASES WERE REPORTES BY REGION AND PER MONTH?--
SELECT  MONTH, CASESREPORTED, R.NAME AS REGION
FROM DBO.HEALTHPERSONNEL HP
LEFT JOIN DBO.STATES S ON HP.REGIONCODE = S.REGIONCODE
JOIN DBO.REGIONS R ON R.ID = HP.REGIONCODE
ORDER BY MONTH ASC, REGION ASC

SELECT  R.NAME AS REGION, SUM(CASESREPORTED) AS TOTALCASESREPORTED
FROM DBO.HEALTHPERSONNEL HP
LEFT JOIN DBO.STATES S ON HP.REGIONCODE = S.REGIONCODE
JOIN DBO.REGIONS R ON R.ID = HP.REGIONCODE
GROUP BY R.NAME


--HOW MANY CASES ARE STATES ARE REPORTING EACH MONTH?--
SELECT MONTHS, STATENAME, CASESREPORTED
FROM DBO.DAILYSTATS DS 
LEFT JOIN DBO.STATES S ON DS.MONTHNUM = S.MONTHNUM

SELECT MONTHS, SUM(CASESREPORTED) AS TOTALCASESREPORTED
FROM DBO.DAILYSTATS DS 
LEFT JOIN DBO.STATES S ON DS.MONTHNUM = S.MONTHNUM
GROUP BY MONTHS

SELECT STATENAME, SUM(CASESREPORTED) AS TOTALCASESREPORTED
FROM DBO.DAILYSTATS DS 
LEFT JOIN DBO.STATES S ON DS.MONTHNUM = S.MONTHNUM
GROUP BY STATENAME

--STATE WITH THE HIGHEST REPORTED CASES--
SELECT STATENAME, MAX(CASESREPORTED) AS HIGHESTCASE
FROM DBO.STATES
GROUP BY STATENAME
ORDER BY HIGHESTCASE DESC